package gui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;
import javax.swing.border.EmptyBorder;

import com.benwaffle.pslib.PSlib;

@SuppressWarnings("serial")
public class LoginWindow extends JFrame {

	private JPanel contentPane;
	private JTextField usernameField;
	public JPasswordField passwordField;
	public JTextField serverField;
	private JLabel usernameLbl;
	private JLabel passwordLbl;
	private JLabel serverLbl;

	private Thread psInit, loginT;
	private PSlib lib;
	
	/**
	 * Generated by window builder
	 */
	public LoginWindow(Thread ps) {
		psInit = ps;
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.setLayout(new BorderLayout(0, 0));
		setContentPane(contentPane);
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[]{115, 235, 0};
		gridBagLayout.rowHeights = new int[]{36, 0, 0, 0, 0, 0, 0, 0, 0};
		gridBagLayout.columnWeights = new double[]{0.0, 0.0, Double.MIN_VALUE};
		gridBagLayout.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		getContentPane().setLayout(gridBagLayout);
		
		JLabel title = new JLabel("GradeTool");
		title.setFont(new Font("Arial", Font.PLAIN, 30));
		title.setHorizontalAlignment(SwingConstants.CENTER);
		GridBagConstraints gbc_lblGradetool = new GridBagConstraints();
		gbc_lblGradetool.insets = new Insets(0, 0, 5, 0);
		gbc_lblGradetool.gridx = 1;
		gbc_lblGradetool.gridy = 1;
		getContentPane().add(title, gbc_lblGradetool);
		
		JLabel loginToPSLbl = new JLabel("Login to PowerSchool");
		loginToPSLbl.setFont(new Font("Arial", Font.PLAIN, 13));
		loginToPSLbl.setHorizontalAlignment(SwingConstants.CENTER);
		GridBagConstraints gbc_lblLoginToPowerschool = new GridBagConstraints();
		gbc_lblLoginToPowerschool.fill = GridBagConstraints.HORIZONTAL;
		gbc_lblLoginToPowerschool.insets = new Insets(0, 0, 5, 0);
		gbc_lblLoginToPowerschool.gridx = 1;
		gbc_lblLoginToPowerschool.gridy = 2;
		getContentPane().add(loginToPSLbl, gbc_lblLoginToPowerschool);
		
		usernameLbl = new JLabel("Username");
		usernameLbl.setFont(new Font("Arial", Font.PLAIN, 13));
		GridBagConstraints gbc_lblNewLabel = new GridBagConstraints();
		gbc_lblNewLabel.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel.anchor = GridBagConstraints.EAST;
		gbc_lblNewLabel.gridx = 0;
		gbc_lblNewLabel.gridy = 3;
		getContentPane().add(usernameLbl, gbc_lblNewLabel);
		
		usernameField = new JTextField();
		GridBagConstraints gbc_txtUsername = new GridBagConstraints();
		gbc_txtUsername.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtUsername.insets = new Insets(0, 0, 5, 0);
		gbc_txtUsername.gridx = 1;
		gbc_txtUsername.gridy = 3;
		getContentPane().add(usernameField, gbc_txtUsername);
		usernameField.setColumns(10);
		
		passwordLbl = new JLabel("Password");
		passwordLbl.setFont(new Font("Arial", Font.PLAIN, 13));
		GridBagConstraints gbc_lblNewLabel_1 = new GridBagConstraints();
		gbc_lblNewLabel_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel_1.anchor = GridBagConstraints.EAST;
		gbc_lblNewLabel_1.gridx = 0;
		gbc_lblNewLabel_1.gridy = 4;
		getContentPane().add(passwordLbl, gbc_lblNewLabel_1);
		
		passwordField = new JPasswordField();
		GridBagConstraints gbc_passwordField = new GridBagConstraints();
		gbc_passwordField.insets = new Insets(0, 0, 5, 0);
		gbc_passwordField.fill = GridBagConstraints.HORIZONTAL;
		gbc_passwordField.gridx = 1;
		gbc_passwordField.gridy = 4;
		getContentPane().add(passwordField, gbc_passwordField);
		
		serverLbl = new JLabel("Server");
		serverLbl.setFont(new Font("Arial", Font.PLAIN, 13));
		GridBagConstraints gbc_lblNewLabel_2 = new GridBagConstraints();
		gbc_lblNewLabel_2.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel_2.anchor = GridBagConstraints.EAST;
		gbc_lblNewLabel_2.gridx = 0;
		gbc_lblNewLabel_2.gridy = 5;
		getContentPane().add(serverLbl, gbc_lblNewLabel_2);
		
		serverField = new JTextField();
		GridBagConstraints gbc_txtServer = new GridBagConstraints();
		gbc_txtServer.insets = new Insets(0, 0, 5, 0);
		gbc_txtServer.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtServer.gridx = 1;
		gbc_txtServer.gridy = 5;
		getContentPane().add(serverField, gbc_txtServer);
		serverField.setColumns(10);
		
		JButton loginButton = new JButton("Login");
		loginButton.setFont(new Font("Arial", Font.PLAIN, 13));
		GridBagConstraints gbc_btnLogin = new GridBagConstraints();
		gbc_btnLogin.insets = new Insets(0, 0, 5, 0);
		gbc_btnLogin.gridx = 1;
		gbc_btnLogin.gridy = 6;
		getContentPane().add(loginButton, gbc_btnLogin);
		
		loginButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				login();
			}
		});
		
		setVisible(true);
	}

	public void login(){
		try {
			if (psInit.isAlive())
				psInit.wait(); // wait until finished init()
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		if (lib == null){
			lib = new PSlib(serverField.getText());
		}
		
		loginT = new Thread(new Runnable() {
			@Override
			public void run() {
				try {
					System.out.println("logging in");
					lib.login(usernameField.getText(), new String(passwordField.getPassword()));
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, "Wrong username or password!", 
							"Error", JOptionPane.ERROR_MESSAGE);
					return;
				}
				userLoggedIn();
			}
		});
		loginT.start();
	}
	
	private void userLoggedIn(){
		new MainWindow(lib);
		setVisible(false);
		dispose();
	}
}
